# Setup
title: Data Analytics with Python & R
tagline:      Statistics, Data Mining, Machine Learning and Deep Learning
baseurl:      ""
paginate:     1

# About/contact
repo1:
  name:       Python Repository
  url:        https://github.com/woosa7/PythonDataAnalytics

repo2:
  name:       R Repository
  url:        https://github.com/woosa7/RDataAanlytics

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown